sudo: required

language: python
python:
  - "2.7"
  - "3.6"

services:
- docker

install:
- echo "Nothing to do"

script:
# Need to find the branch name containing the last commit
# `git branch` has format '  <my branch>' so need to remove the 2 leading spaces:
- branch=$(git branch --contains `git rev-parse HEAD` | tail -n 1)
- docker build -t louisleblin/spinnaker-examples:8 --build-arg GIT_CHECKOUT_TO="${branch:2}" .

# Publish on DockerHub
deploy:
  provider: script
  script: 'if [ "${TRAVIS_PYTHON_VERSION}" = "2.7" ]; then ./scripts/docker_push ; fi'
  on:
    branch: master

notifications:
  email: false
